baseURL = "https://androidscroll.gwill.workers.dev/"
languageCode = "en-us"
title = "My Blog"
theme = "PaperMod"

[params]
  description = "My personal blog"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
